# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -o disshkographia

      - name: Test
        run: go test -v

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DISKOGRAPHIA_HOST }}
          port: ${{ secrets.DISKOGRAPHIA_PORT }}
          username: ${{ secrets.DISKOGRAPHIA_USER }}
          key: ${{ secrets.DISKOGRAPHIA_SSH_PRIVATE_KEY }}
          source: disshkographia
          target: ${{ secrets.DISKOGRAPHIA_TARGET_DIR }}

      - name: Restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DISKOGRAPHIA_HOST }}
          port: ${{ secrets.DISKOGRAPHIA_PORT }}
          username: ${{ secrets.DISKOGRAPHIA_USER }}
          key: ${{ secrets.DISKOGRAPHIA_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart disshkographia
